packages:
  # core = 开发用的代码依赖（库）#303
  - core/*
  - core/adapters/*
  - core/adapters/provisioning/*
  # app = 开发好的 app，可被装配（全部发 npm）#303
  - app/workbench
  - app/installer
  - app/modules/*
  - app/modules/*/frontend
allowBuilds:
  esbuild: true
  workerd: true
