// SPDX-License-Identifier: AGPL-3.0-only
import { Hono } from 'hono';
import type { Bindings, CoreApiDependencies } from '../index';
import { readSession } from '../session';
import { audit } from '../services/audit';
type Result = { ok: boolean; detail: string };
const s=(v:unknown)=>typeof v==='string'?v:'';
const p=(r?:string)=>{try{const v=r?JSON.parse(r):{};return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};}catch{return {};}};
const f=(e:unknown,sender:boolean):Result=>{const m=e instanceof Error?e.message:String(e);if(!sender&&/401|403|unauthor|api.?key/i.test(m))return{ok:false,detail:'认证失败，请检查 API Key（管理员账号+Inherit）'};if(sender&&/auth|535|credential|password|username/i.test(m))return{ok:false,detail:'SMTP 凭据错误，请检查 SMTP 用户名密码'};return{ok:false,detail:`${sender?'SMTP 连接失败，请检查 host/port 与防火墙':'连接失败，请检查 Stalwart 地址与防火墙'}（${m}）`};};
async function j(c:Record<string,unknown>):Promise<Result>{const b=s(c.baseUrl),k=s(c.apiKey),d=s(c.domain);if(!b||!k||!d)return{ok:false,detail:'请先保存完整的 Stalwart 地址、API Key 与邮箱域名配置'};const r=await fetch(`${b.replace(/\/+$/,'')}/jmap`,{method:'POST',headers:{Authorization:`Bearer ${k}`,'Content-Type':'application/json'},body:JSON.stringify({using:['urn:ietf:params:jmap:core','urn:stalwart:jmap'],methodCalls:[['x:Domain/query',{filter:{name:d}},'d']]})});if(!r.ok)throw Error(`HTTP ${r.status}`);const x=(await r.json() as any).methodResponses?.find((v:any)=>Array.isArray(v)&&v[2]==='d');if(!x||x[0]==='error'||!x[1]?.ids?.length)throw Error(`未找到域名 ${d}`);return{ok:true,detail:`已连接，域名 ${d} 可用`};}
async function m(c:Record<string,unknown>):Promise<Result>{const h=s(c.host),u=s(c.username),pw=s(c.password),fr=s(c.from),po=Number(c.port);if(!h||!po||!u||!pw||!fr)return{ok:false,detail:'请先保存完整的 SMTP host、port、用户名、密码与发件地址配置'};const {connect}=await import('cloudflare:sockets');const so=connect({hostname:h,port:po,secureTransport:'on'});await so.opened;const rd=so.readable.getReader(),wr=so.writable.getWriter(),e=new TextEncoder(),d=new TextDecoder();let b='';const read=async()=>{for(;;){const i=b.indexOf('\n');if(i>=0){const l=b.slice(0,i).replace(/\r$/,'');b=b.slice(i+1);return l;}const n=await rd.read();if(n.done)throw Error('连接中断');b+=d.decode(n.value,{stream:true});}};const cmd=async(a:number,z:number,l?:string)=>{if(l)await wr.write(e.encode(`${l}\r\n`));let q=await read();while(/^\d{3}-/.test(q))q=await read();const n=Number(q.slice(0,3));if(n<a||n>z)throw Error(`SMTP ${n}`);};try{await cmd(220,220);await cmd(250,299,`EHLO ${fr.split('@')[1]??'unself'}`);await cmd(334,334,'AUTH LOGIN');await cmd(334,334,btoa(u));await cmd(235,235,btoa(pw));await cmd(200,399,'RSET');await wr.write(e.encode('QUIT\r\n'));return{ok:true,detail:'SMTP 连接、认证与退出测试成功（未投递邮件）'};}finally{try{wr.releaseLock();}catch{}await so.close().catch(()=>{});}}
export function registerMailTestRoutes(app:Hono<{Bindings:Bindings}>,deps:CoreApiDependencies={}):void{app.post('/api/admin/mail/test',async c=>{const row=await c.env.CORE_DB.prepare("SELECT value FROM instance_config WHERE key = 'mail'").bind().first<{value:string}>();const cfg=p(row?.value);let provisioner:Result,sender:Result;try{const x=deps.createMailProvisioner?.(cfg) as any;provisioner=x?.testConnection?(await x.testConnection(),{ok:true,detail:'Provisioner 连接测试成功'}):await j(cfg);}catch(e){provisioner=f(e,false);}try{const x=deps.createMailSender?.(cfg) as any; sender=x?.testConnection?(await x.testConnection(),{ok:true,detail:'SMTP 连接、认证与退出测试成功（未投递邮件）'}):await m(cfg);}catch(e){sender=f(e,true);}const se=await readSession(c);if(se)await audit(c.env.CORE_DB,se.uid,'mail_tested');return c.json({provisioner,sender});});}
