name: sync-to-gitea

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitea
        run: |
          git remote add gitea "https://Handy_Wote:${GITEA_TOKEN}@git.unself.cn/UnSelf/unself.git"
          git push gitea main --force-with-lease
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
